name: game_maybe
description: Flame game?
version: 0.0.0
publish_to: none

environment:
  sdk: ^2.16.0
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.7.0
  shared_preferences: ^2.1.0

flutter:
  assets:
    - assets/images/